### ISSUE TITLE
"Open With" Outside Services

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#688]
I just pushed a PR https://github.com/NuCivic/dkan_dataset/pull/150 that does two things:

## Offers 3 Dataset Teaser Preview Modes:
<img width="1205" alt="screen shot 2015-09-01 at 7 36 22 am" src="https://cloud.githubusercontent.com/assets/512243/9604278/2f5cf408-507c-11e5-8967-1e74668cf6f3.png">

These are configurable at ``/admin/dkan/dataset_teaser``.

TODO:

- [ ] Provide internal screenshots of difference between the options.

## Enhanced Dataset Preview
This PR adds two additional Dataset teaser options as well as an option to keep the original.

### Explore
This looks like https://www.opendataphilly.org/dataset/airport-buildings

For resources that have an uploaded file it provides a "preview" dropdown:
<img width="866" alt="screen shot 2015-08-31 at 11 20 25 pm" src="https://cloud.githubusercontent.com/assets/512243/9604317/7ebd2770-507c-11e5-82b1-24ecf5481b97.png">

For resources that have a link it provides a "go to resource" dropdown:
<img width="874" alt="screen shot 2015-08-31 at 11 20 35 pm" src="https://cloud.githubusercontent.com/assets/512243/9604323/88501bbc-507c-11e5-8ce8-38cfca72e5ed.png">

### "Open With" Preview
This is similar to: http://catalog.data.gov/dataset/shipping-lanes-in-u-s-waters

It provides the ability to open a resource in an outside service and provides the default "DKAN Preview" for CSV files.

<img width="840" alt="screen shot 2015-08-31 at 11 22 47 pm" src="https://cloud.githubusercontent.com/assets/512243/9604367/c5b82760-507c-11e5-8b46-f31f4dd5520a.png">

New services can be added using ``hook_dkan_dataset_open_with_alter``.

This is particularly useful for ArcGIS REST Endpoint previews for North Dakota but would also allow users to "Open With" CartoDB or Dataseed or other viz providers.

## What this solves

1. Easier direct link to resources, especially those that don't have a data preview. On HHS for example most files are not CSVs so it is an unnecessary extra step to ask people to click through to the resources.
2. "Open With" functionality offers easier integration for users with outside services. The "Open With" preview is not turned on by default so it will only appear with folks that explicitly want to use outside services.

## TODO:

- [ ] Get Dev QA
- [ ] Add tests
- [ ] Get CSS QA from Janette
- [ ] Document
- [ ] Talk about strategy for outside services (should we add CartoDB as a default? Dataseed?)

**Comment by acouch** [comment]
PR is here https://github.com/NuCivic/dkan_dataset/pull/161
