### ISSUE TITLE
Support more data formats in dataset previews

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan#738]
## Description

 **Improved resource data preview.** We will now be able to preview JSON, XML, GeoJSON, WMS, ArcGIS REST endpoint, PDF file types. The preview will also be the same no matter if the file is linked to or uploaded.

Preview types are determined by the `format` taxonomy. There is no discover mechanism in Recline to figure out what the type of file it previews:

``` php
  switch ($type) {
    case 'json':
      $output['preview'] = recline_preview_json($url);
      break;
    case 'csv':
      $output['preview'] = recline_preview_csv($url, $file, $vars);
      break;
    case 'geojson':
      $output['preview'] = recline_preview_geojson_leaflet($url);
      break;
```
## User Stories

``` yaml
As a user with the "authenticated user" role
When I upload a (XML | CSV etc... see acceptance criteria)
I should see a (map | image | tree etc...)
```
## Tests

These weren't written b/c of changing strategies with behat and outside services. More to come.
## Documentation

Need to update DKAN Docs with additional file type capabilities
## Pull Requests
- https://github.com/NuCivic/recline/pull/32
## Acceptance Criteria

After tests pass, previews should work on resources no matter if they are uploads or links for the following file types:
- [ ] CSV [File 1](http://demo.getdkan.com/sites/default/files/Polling_Places_Madison_0.csv), [File 2](http://www.nd.gov/gis/apps/BedrockGeology.csv), [File 3](https://data.wa.gov/api/views/mu24-67ke/rows.csv?accessType=DOWNLOAD)
- [ ] JSON [File 1](https://data.wa.gov/api/views/mu24-67ke/rows.json?accessType=DOWNLOAD)
- [ ] GeoJSON [File 1](http://api.tiles.mapbox.com/v3/tmcw.map-gdv4cswo/markers.geojson)
- [ ] Image [File 1](http://gisdata.nd.gov/Metadata/Images/counties.png)
- [ ] WMS [Link 1](http://ndgishub.nd.gov/arcgis/services/All_Communications/MapServer/WMSServer?)
- [ ] ArcGIS REST Endpoint [File 1](http://ndgishub.nd.gov/arcgis/rest/services/All_Communications/MapServer/)
- [ ] ZIP [File 1](https://health.data.ny.gov/api/file_data/QLQGgv7WxWH8JDrpbySPD-y7pk4AYw9957WUVl1umwM?filename=NYSDOH_NHCostReport_2011.zip)
- [ ] XML [File 1](http://gisdata.nd.gov/Metadata/ISO/counties.xml)
- [ ] RDF [File 1](http://omes.prod.acquia-sites.com/sites/default/files/res_state_of_oklahoma_payroll_calendar_year_2015_ntv8-isvj.rdf)
## TODOs
- [ ] Articulate testing strategy

**Comment by acouch** [comment]
I'm working on filling out the ticket.

**Comment by akuckartz** [comment]
Why was this closed?
