### ISSUE TITLE
Improve user profile page

### ISSUE THREAD

**Issue by janette** [NuCivic/dkan#989]
## User Story
As a *site editor*,
I want to *have a clear and concise user page*
so that *I can easily see the information pertinent to me*.
 
## Description
 The user page is visually hideous

## Tasks
- [ ] Update facet block titles  https://github.com/NuCivic/dkan/issues/1018
- [ ] Move the content from the 'Groups' and 'About' tabs into the sidebar user block
- [ ] Re-title the search results to 'Your Content' rather than 'Datasets'

## Acceptance Criteria
When I go to my user page:
•  I should see a list of my content that is titled "My Content"
•  I should see the groups that I belong to in the left sidebar
•  I should see that the facet filters are titled the same as on the dataset search page

**Comment by janette** [comment]
done https://github.com/NuCivic/dkan/pull/1046
